"""Add git platform columns to workspace table

Revision ID: b1c2d3e4f5a6
Revises: a9f4cd2e4f57
Create Date: 2026-04-22 15:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5a6'
down_revision = 'a9f4cd2e4f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('git_access_token', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('git_platform_url', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('git_platform_type', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('git_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'git_username')
    op.drop_column('workspace', 'git_platform_type')
    op.drop_column('workspace', 'git_platform_url')
    op.drop_column('workspace', 'git_access_token')
    # ### end Alembic commands ###
